services:
  api:
    container_name: express-app
    image: express-app
    ports:
      - 4000:4000

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest

  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=intelparcel
      - POSTGRES_PASSWORD=IntelParcel@21
      - POSTGRES_DB=intelparcel_db
